name: Create Release

on:
  push:
    tags:
      - 'v*' # Memicu workflow ini jika Anda membuat tag yang berawalan 'v' (misal: v1.0.0)

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build node.exe
        run: cargo build --bin node --release

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/node.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
